export const INITIAL_DICE_STATES = {
  WAITING: "WAITING",
  ROLLING: "ROLLING",
  REROLL_NEEDED: "REROLL_NEEDED",
  COMPLETED: "COMPLETED",
};

export const PLAYER_ACTIONS = {
  DRAW_VISIBLE: "DRAW_VISIBLE",
  DRAW_HIDDEN: "DRAW_HIDDEN",
  PASS: "PASS",
};
